# Supabase Project Config
SUPABASE_URL=https://kanbhhxmmbmaiohrifzy.supabase.co
SUPABASE_ANON_KEY=sb_publishable_5hZmE83oW0T6c72zqrheww_Ful3uvMF

# Database (Postgres direct connection)
DATABASE_URL=postgresql://postgres:[YOUR-PASSWORD]@db.kanbhhxmmbmaiohrifzy.supabase.co:5432/postgres
